plugins:
  journal_enabled:
    client: true
    default: true
  journal_show_topic_tip:
    client: true
    default: true
  journal_comments_default:
    default: 3
    client: true
  journal_comments_expanded_per_page:
    default: 10
    client: true
